# Generated by Django 3.0 on 2020-09-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='description',
            field=models.TextField(blank=True, max_length=64, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=128)),
                ('image', models.ImageField(blank=True, upload_to='products_image')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Размер')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CategoryProduct')),
            ],
        ),
    ]
