# Generated by Django 3.0 on 2020-10-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users_avatar', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.CharField(max_length=64, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='username',
            field=models.CharField(max_length=64, unique=True, verbose_name='Логин'),
        ),
    ]
