# Generated by Django 3.1.2 on 2020-11-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20201113_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
