# Generated by Django 3.1.2 on 2020-11-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'формируется'), ('STP', 'отправлен на обработку'), ('PRD', 'обрабатывается'), ('PD', 'оплачен'), ('CNC', 'отменен'), ('RDY', 'готов к выдаче')], default='FM', max_length=3, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлен'),
        ),
    ]
